// Code generated by tug gen from the Go types. DO NOT EDIT.

export interface ErrorPageProps {
  status: number
  message: string
}

export interface PageLink {
  url: string | null
  label: string
  active: boolean
}

export interface Paginated_Post {
  current_page: number
  data: Post[]
  first_page_url: string
  from: number | null
  last_page: number
  last_page_url: string
  links: PageLink[]
  next_page_url: string | null
  path: string
  per_page: number
  prev_page_url: string | null
  to: number | null
  total: number
}

export interface Post {
  id: number
  title: string
  body: string
  tags: string[]
}

export interface PostsArchiveProps {
  posts: Paginated_Post
}

export interface PostsCreateProps {}

export interface PostsEditProps {
  post: Post
}

export interface PostsIndexProps {
  posts: { data: Post[] }
  stats?: Stats
}

export interface PostsShowProps {
  post: Post
}

export interface Stats {
  posts: number
  words: number
}

// SharedProps are the props every page gets from inertia.Share. A prop that
// ShareFunc works out per request is here too when Share gives it a first
// value, as Share("auth", Auth{}) does; or it can be added from another
// file:
//
//   declare module './pages' { interface SharedProps { user: User } }
export interface SharedProps {
  appName: string
}

// Pages are the props of each page component, as tug.Page declares them.
export interface Pages {
  'Error': ErrorPageProps
  'Posts/Archive': PostsArchiveProps
  'Posts/Create': PostsCreateProps
  'Posts/Edit': PostsEditProps
  'Posts/Index': PostsIndexProps
  'Posts/Show': PostsShowProps
}

// PageProps are everything a page component gets: its own props, and the
// shared ones.
export type PageProps<C extends keyof Pages> = Pages[C] & SharedProps

// FlashData is the flash data a handler leaves for the next page, by the keys
// tug.Flash declares, for usePage().flash: a page has some of them, or none.
export interface FlashData {
  success?: string
}

declare module '@inertiajs/core' {
  export interface InertiaConfig {
    sharedPageProps: SharedProps
    flashDataType: FlashData
  }
}
