// Code generated by tug gen from the Go types. DO NOT EDIT.

// routes are the app's named routes: the method each takes, and the path
// pattern its URL is built from.
export const routes = {
  'posts.create': { method: 'get', path: '/posts/create' },
  'posts.destroy': { method: 'delete', path: '/posts/{id}' },
  'posts.edit': { method: 'get', path: '/posts/{id}/edit' },
  'posts.index': { method: 'get', path: '/{$}' },
  'posts.show': { method: 'get', path: '/posts/{id}' },
  'posts.store': { method: 'post', path: '/posts' },
  'posts.update': { method: 'put', path: '/posts/{id}' },
} as const

// Params are the values each route's path needs, one for each wildcard.
export interface Params {
  'posts.create': Record<string, never>
  'posts.destroy': { id: string | number }
  'posts.edit': { id: string | number }
  'posts.index': Record<string, never>
  'posts.show': { id: string | number }
  'posts.store': Record<string, never>
  'posts.update': { id: string | number }
}

export type RouteName = keyof Params

// route builds the path of a named route, filling its wildcards with params,
// as App.URL does in Go:
//
//   route('posts.show', { id: 42 }) // '/posts/42'
export function route<N extends RouteName>(
  name: N,
  ...[params]: Params[N] extends Record<string, never> ? [params?: Params[N]] : [params: Params[N]]
): string {
  const values = (params ?? {}) as Record<string, string | number>
  return routes[name].path.replace(/\{([^}]*)\}/g, (_, token: string) => {
    if (token === '$') {
      return ''
    }
    if (token.endsWith('...')) {
      return String(values[token.slice(0, -3)] ?? '').split('/').map(encodeURIComponent).join('/')
    }
    return encodeURIComponent(String(values[token]))
  })
}
