// Package typegen writes the TypeScript that mirrors a tug app's Go: the
// props each page takes, the props every page shares, and the app's named
// routes. tug gen puts it in resources/js/tug, so a page's props and a
// route's parameters are checked by the TypeScript compiler as they are by
// Go's.
package typegen

import (
	"cmp"
	"encoding"
	"encoding/json"
	"fmt"
	"maps"
	"reflect"
	"slices"
	"strings"
	"time"
)

// Page is a page component and its props type, as tug.Page declares them.
type Page struct {
	Component string
	Props     reflect.Type
}

// Route is a named route.
type Route struct {
	Name   string
	Method string // "" for any
	Path   string // a ServeMux path pattern, as "/posts/{id}"
}

// Input is what the TypeScript is written from.
type Input struct {
	Pages  []Page
	Shared map[string]any // the props shared with inertia.Share, by value
	Routes []Route
}

// Output is the TypeScript: pages.ts and routes.ts.
type Output struct {
	Pages  string `json:"pages"`
	Routes string `json:"routes"`
}

// header marks the files as written by tug gen, so that tools and people
// leave them alone.
const header = "// Code generated by tug gen from the Go types. DO NOT EDIT.\n"

// Generate writes the TypeScript for in.
func Generate(in Input) Output {
	return Output{Pages: pages(in), Routes: routes(in.Routes)}
}

func pages(in Input) string {
	g := &gen{decls: map[string]string{}, names: map[reflect.Type]string{}, taken: map[string]reflect.Type{}}

	pages := slices.Clone(in.Pages)
	slices.SortFunc(pages, func(a, b Page) int { return cmp.Compare(a.Component, b.Component) })
	var pageTypes []string
	for _, p := range pages {
		pageTypes = append(pageTypes, fmt.Sprintf("  %s: %s", quote(p.Component), g.propsType(p.Props)))
	}

	var shared []string
	for _, key := range slices.Sorted(maps.Keys(in.Shared)) {
		t := reflect.TypeOf(in.Shared[key])
		ts, optional := "unknown", false
		if t != nil {
			ts, optional = g.fieldType(t)
		}
		shared = append(shared, fmt.Sprintf("  %s%s: %s", property(key), cond(optional, "?", ""), ts))
	}

	var b strings.Builder
	b.WriteString(header)
	for _, name := range slices.Sorted(maps.Keys(g.decls)) {
		b.WriteString("\n" + g.decls[name])
	}
	b.WriteString("\n// SharedProps are the props every page gets from inertia.Share. A prop that\n")
	b.WriteString("// ShareFunc works out per request is here too when Share gives it a first\n")
	b.WriteString("// value, as Share(\"auth\", Auth{}) does; or it can be added from another\n")
	b.WriteString("// file:\n")
	b.WriteString("//\n//   declare module './pages' { interface SharedProps { user: User } }\n")
	b.WriteString("export interface SharedProps {\n" + lines(shared) + "}\n")
	b.WriteString("\n// Pages are the props of each page component, as tug.Page declares them.\n")
	b.WriteString("export interface Pages {\n" + lines(pageTypes) + "}\n")
	b.WriteString("\n// PageProps are everything a page component gets: its own props, and the\n// shared ones.\n")
	b.WriteString("export type PageProps<C extends keyof Pages> = Pages[C] & SharedProps\n")
	b.WriteString("\ndeclare module '@inertiajs/core' {\n  export interface InertiaConfig {\n    sharedPageProps: SharedProps\n  }\n}\n")
	return b.String()
}

func lines(ls []string) string {
	if len(ls) == 0 {
		return ""
	}
	return strings.Join(ls, "\n") + "\n"
}

func cond(ok bool, yes, no string) string {
	if ok {
		return yes
	}
	return no
}

// gen collects the interfaces the types need, one for each named struct.
type gen struct {
	decls map[string]string       // TypeScript name → declaration
	names map[reflect.Type]string // Go type → TypeScript name
	taken map[string]reflect.Type // TypeScript name → the Go type it's for
}

// propsType is the TypeScript type of a page's props.
func (g *gen) propsType(t reflect.Type) string {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	if t.Kind() == reflect.Struct {
		return g.typeOf(t)
	}
	return "Record<string, unknown>"
}

var (
	timeType          = reflect.TypeFor[time.Time]()
	jsonMarshalerType = reflect.TypeFor[json.Marshaler]()
	textMarshalerType = reflect.TypeFor[encoding.TextMarshaler]()
	rawMessageType    = reflect.TypeFor[json.RawMessage]()
)

// fieldType is the TypeScript type of a field of type t, and whether the
// field can be missing: a deferred or optional prop is, until the client
// fetches it.
func (g *gen) fieldType(t reflect.Type) (string, bool) {
	if kind, inner, ok := propOf(t); ok {
		switch kind {
		case "ScrollProp":
			return "{ data: " + array(g.typeOf(inner)) + " }", false
		case "DeferProp", "OptionalProp":
			return g.typeOf(inner), true
		}
		return g.typeOf(inner), false
	}
	return g.typeOf(t), false
}

// propOf reports whether t is one of package inertia's prop types, which
// go out as the value they hold, and returns its kind and that value's type.
func propOf(t reflect.Type) (string, reflect.Type, bool) {
	if t.PkgPath() != "github.com/cuonggt/tug/inertia" || t.Kind() != reflect.Struct {
		return "", nil, false
	}
	kind, _, generic := strings.Cut(t.Name(), "[")
	if !generic {
		return "", nil, false
	}
	switch kind {
	case "AlwaysProp":
		return kind, t.Field(0).Type, true
	case "LazyProp", "OptionalProp", "DeferProp", "MergeProp", "OnceProp":
		return kind, t.Field(0).Type.Out(0), true // fn func() (T, error)
	case "ScrollProp":
		return kind, t.Field(0).Type.Out(0).Elem(), true // fn func() ([]T, Paging, error)
	}
	return "", nil, false
}

// typeOf is the TypeScript type of a value of type t, as encoding/json
// writes it.
func (g *gen) typeOf(t reflect.Type) string {
	switch {
	case t == timeType:
		return "string"
	case t == rawMessageType:
		return "unknown"
	}
	if _, _, ok := propOf(t); ok {
		ts, _ := g.fieldType(t)
		return ts
	}
	if t.Kind() != reflect.Pointer && t.Kind() != reflect.Interface {
		switch {
		case t.Implements(jsonMarshalerType) || reflect.PointerTo(t).Implements(jsonMarshalerType):
			return "unknown"
		case t.Implements(textMarshalerType) || reflect.PointerTo(t).Implements(textMarshalerType):
			return "string"
		}
	}
	switch t.Kind() {
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Pointer:
		return g.typeOf(t.Elem()) + " | null"
	case reflect.Slice, reflect.Array:
		if t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Uint8 {
			return "string" // encoding/json writes a []byte as base64, and a [N]byte as numbers
		}
		return array(g.typeOf(t.Elem()))
	case reflect.Map:
		return "Record<string, " + g.typeOf(t.Elem()) + ">"
	case reflect.Struct:
		if t.Name() == "" {
			return g.object(t, false)
		}
		return g.named(t)
	}
	return "unknown" // interfaces, and what encoding/json can't write
}

// array is the TypeScript array of elem.
func array(elem string) string {
	if strings.Contains(elem, "|") || strings.Contains(elem, "&") {
		return "(" + elem + ")[]"
	}
	return elem + "[]"
}

// named declares an interface for a named struct, once, and returns its
// name.
func (g *gen) named(t reflect.Type) string {
	if name, ok := g.names[t]; ok {
		return name
	}
	name := identifier(t.Name())
	if other, ok := g.taken[name]; ok && other != t {
		pkg := t.PkgPath()[strings.LastIndex(t.PkgPath(), "/")+1:]
		name = identifier(pkg) + "_" + name // two packages with a type of the same name
	}
	g.names[t] = name
	g.taken[name] = t
	g.decls[name] = "export interface " + name + " " + g.object(t, true) + "\n"
	return name
}

// identifier makes a Go type name, which may be a generic instance such as
// "Page[main.Post]", into a TypeScript name, "Page_Post".
func identifier(name string) string {
	var b strings.Builder
	for _, part := range strings.FieldsFunc(name, func(r rune) bool { return r == '[' || r == ']' || r == ',' || r == ' ' || r == '*' }) {
		if i := strings.LastIndex(part, "."); i >= 0 {
			part = part[i+1:]
		}
		if b.Len() > 0 {
			b.WriteByte('_')
		}
		b.WriteString(part)
	}
	return b.String()
}

// object is the TypeScript object type of a struct, with the fields
// encoding/json writes: a line each for an interface, or on one line for an
// anonymous struct.
func (g *gen) object(t reflect.Type, multiline bool) string {
	var fields []string
	g.fields(t, &fields)
	switch {
	case len(fields) == 0:
		return "{}"
	case multiline:
		return "{\n  " + strings.Join(fields, "\n  ") + "\n}"
	}
	return "{ " + strings.Join(fields, "; ") + " }"
}

func (g *gen) fields(t reflect.Type, out *[]string) {
	for i := range t.NumField() {
		sf := t.Field(i)
		tag := sf.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name, opts, _ := strings.Cut(tag, ",")
		ft := sf.Type
		if sf.Anonymous && name == "" {
			if ft.Kind() == reflect.Pointer {
				ft = ft.Elem()
			}
			if ft.Kind() == reflect.Struct {
				g.fields(ft, out) // promoted, as encoding/json promotes them
				continue
			}
		}
		if !sf.IsExported() {
			continue
		}
		if name == "" {
			name = sf.Name
		}
		ts, optional := g.fieldType(sf.Type)
		options := strings.Split(opts, ",")
		if slices.Contains(options, "omitempty") || slices.Contains(options, "omitzero") {
			optional = true
		}
		if slices.Contains(options, "string") {
			ts = "string"
		}
		*out = append(*out, property(name)+cond(optional, "?", "")+": "+ts)
	}
}

// property is a name as a TypeScript property: bare when it can be, and
// quoted when it can't.
func property(name string) string {
	for i, r := range name {
		if !(r == '_' || r == '$' || 'a' <= r && r <= 'z' || 'A' <= r && r <= 'Z' || i > 0 && '0' <= r && r <= '9') {
			return quote(name)
		}
	}
	if name == "" {
		return quote(name)
	}
	return name
}

func quote(s string) string {
	b, _ := json.Marshal(s)
	return "'" + strings.ReplaceAll(strings.Trim(string(b), `"`), "'", `\'`) + "'"
}
